### ISSUE TITLE
AdysTech.InfluxDB.Client.Net.ServiceUnavailableException: InfluxDB service is not available

### ISSUE THREAD

**Issue by micheleBridi** [AdysTech/InfluxDB.Client.Net#102]
Hello,
when i do this query:
"select median (Value), time from Tags WHERE time> = '2020-11-13T00: 00: 00Z' AND time <= '2020-11-14T00: 00: 00Z' and Client = 'MommioExor' and TagName = ' Power 'GROUP by time (1h) "
i get this error: (false, {AdysTech.InfluxDB.Client.Net.ServiceUnavailableException: InfluxDB service is not available
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.QueryMultiSeriesAsync (String dbName, String measurementQuery, String retentionPolicy, TimePrecision precision)
   at Hydro.Data.Database.InfluxHydroInfluxContext.GetDataByQuery (String database, String query) in C: \ Work \ Repos \ HYDRO \ Solution \ Hydro \ Hydro.Data \ Database \ InfluxHydroContext.cs: line 69}, null)

if i do the same query inside console of influxDB it works.

i get this error only if i use gruop by, if i don't using it i get all data without any error

**Comment by mvadu** [comment]
I will have to check on the `ServiceUnavailableException` being thrown, but can you check if you r query is correct? `TagName = 'Power 'GROUP by time (1h)` has an extra space in TagName, and no space before GROUP.

**Comment by micheleBridi** [comment]
Good morning, before publishing the query I had tried it in influx and it worked (by copying and pasting)

**Comment by micheleBridi** [comment]
hello, i just retried the query from c #: "select median(Value), time from Tags WHERE time >= '2020-11-17T00:00:00Z' AND time <= '2020-11-18T00:00:00Z' and Client = 'MommioEwon' and TagName = 'Potenza' GROUP by time(1h)"
and it doesn't work while doing it in influx it works
Thank you and good day


![image](https://user-images.githubusercontent.com/74403751/99358572-051ae000-28ae-11eb-9657-f837b77ab3a8.png)

**Comment by micheleBridi** [comment]
@mvadu Hello, were you able to find the error?

**Comment by mvadu** [comment]
Hi, sorry for being late to this. Today I pushed a new version which fixes the way `ServiceUnavailableException`  is built. Can you please retest?

**Comment by micheleBridi** [comment]
Thanks!

Il giorno gio 18 feb 2021 alle ore 06:52 Adarsha <notifications@github.com>
ha scritto:
