### ISSUE TITLE
Excessive memory usage when using InfluxDb.Client.Net when processing large number of measurements

### ISSUE THREAD

**Issue by PatrickKalkman** [AdysTech/InfluxDB.Client.Net#105]
Hi, first of all, thank you very much for creating this InfluxDB client and making it open-source. We are using it on an embedded system to communicate with an InfluxDB server running on the same embedded device to process a large number of measurements.

We recently saw an enormous increase (leakage) in memory usage of one of our services that runs on the device. After some investigation, we saw that the memory leakages was coming from types in the Microsoft.CSharp.RuntimeBinder.Semantics.* namespace. See the screenshot below of running the !dumpheap -stat command in a WinDBG session.

Further investigation revealed that this could be caused by the use of dynamic and expando object which are hosted in the namespaces that I previously mentioned. See, for example, https://stackoverflow.com/questions/42519547/net4-expandoobject-usage-leaking-memory and https://stackoverflow.com/questions/33080252/memory-overflow-having-an-increasing-number-of-microsoft-csharp-runtimebinder-s

The only place where we were using dynamic and expando objects was in communicating with the InfluxDB.Client.Net. Removing this from our code by switching to the strongly typed method variants was not successful.
As a last resort, we changed all the dynamic and expando object usages in InfluxDb.Client.Net to use a Dictionary<string, object> instead.

This actually fixed our problem, we see no more excessive memory usage from the Microsoft.CSharp.RuntimeBinder.Semantics namespace or any other.

This #104 PR includes the changes we made to fix the memory leakage problem. Although the dynamic and expando object solution is somewhat more elegant, the memory usage when you are processing a large number of samples is a serious problem for us.

We created the pull request, to help someone if they have the same problems

![image](https://user-images.githubusercontent.com/124125/103776966-8120e100-5030-11eb-891f-d08bba3a20d2.png)

**Comment by mvadu** [comment]
@PatrickKalkman thank you for bringing this issue up, and sorry for responding late. I have come across the issue with expnado objects in the past in another project too. At the time I  treated it as a price to pay for the luxury of easy to read code. But in an embedded system it does cause a problem.   

Your current PR #104 changes the interface contract itself, which will break all consumers. I rather add a new method exposing the dictionary, and update the original implementation to create the dynamic object from the dictionary. Please look at the review comments I added there.

**Comment by mvadu** [comment]
If you are okay I will close the issue here and we can continue the discussion in the PR comments.

**Comment by PatrickKalkman** [comment]
Hello @mvadu, thank you for your response.

I agree with the remarks you made in the review and I will make the changes you suggested.

Thanks again for creating this InfluxDb client and making it open source!
