### ISSUE TITLE
NullReferenceException in GetAsync/PostAsync catch blocks

### ISSUE THREAD

**Issue by DmitryNaumov** [AdysTech/InfluxDB.Client.Net#107]
We ran into situation when our influxdb instance experiencing issues or is down and during that time the library raises unexpected NullReferenceException. We found that it is because it expects InnerException to be always present, which is the true. And also matching exception cases by string literals is imo subject of system locale. And finally mostly no code is ready to get null instead of HttpResponseMessage.

https://github.com/AdysTech/InfluxDB.Client.Net/blob/master/src/DataStructures/InfluxDBClient.cs#L182

I'll submit a proposed solution later

**Comment by mvadu** [comment]
closed in #108
