### ISSUE TITLE
Does it support the influxdb 2.x?

### ISSUE THREAD

**Issue by jinyanghuang** [AdysTech/InfluxDB.Client.Net#109]
This is a question. Sorry I don't find any instruction for if this support the influxdb 2.x or not.

**Comment by mvadu** [comment]
I haven't worked with Influxdb 2.x, but they still support line protocol, and InfluxQL, so i don't see any reason why it will not work. If you have a 2.x setup, do you mind giving it a quick spin?

**Comment by jinyanghuang** [comment]
Sure I will do a quick check
