### ISSUE TITLE
Create Continuous Query

### ISSUE THREAD

**Issue by ehjk** [AdysTech/InfluxDB.Client.Net#16]
Hello. Is it possible to create a Continuous Query using the Client?

**Comment by mvadu** [comment]
Not as of now. As of now it supports only write(insert) and read(select). Continuous Query needs to be setup only once, and I am not sure you want to depend on a client library to do that. Can you provide a use case?
btw, I am working on a next version with more of DML kind of constructs. I can try to add CQ as part of it.

**Comment by ehjk** [comment]
I have an existing .Net interface that runs on IoT type hardware. They are self-managing in that I am currently using a different time-series historian where it self creates Streams (Measurements) and can set up its own calculations (CQ) to run according to a central configuration. I just wanted to avoid using a Client for some parts of InfluxDB interaction, and then raw query URLs for other parts.

**Comment by mvadu** [comment]
Okay.. if you can wait for a week (or two) I will give you a version with CQ. It will be more like my current implementation of retention policy object model.

**Comment by ehjk** [comment]
A week or two (but not three) should be fine. 
I'm working on 2 week sprints where I am looking to integrate Influx.Db.Net.

**Comment by mvadu** [comment]
@ehjk Can you pls check the latest version (either build your own or pull from Nuget) and verify if the current implementation of CQ work for your needs?

**Comment by ehjk** [comment]
Great, it works as expected. Thank you!

One note...can I delete a previously created CQ? I can't see an obvious option for that. Do I specify that in the Create CQ query?

**Comment by mvadu** [comment]
Sorry for the delay in response. I have a new version coming in tomorrow which will have an option to  Drop CQs.
