### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by ehjk** [AdysTech/InfluxDB.Client.Net#17]
Hello. Do you plan to support .Net Core? I have a Web API built on .Net Core where I will need to access data from InfluxDB.

**Comment by mvadu** [comment]
Do you know mind reading? Yes, that is the idea.. to have a single client library to support both Windows and Linux. But for this I can't make 2 week's promise.

**Comment by ehjk** [comment]
Any ETA on the .Net Core version? I've ported the code myself to .Net core and there are only a few changes to be made.

**Comment by mvadu** [comment]
I am in the middle of an international relocation, so bear with me for a while. Most likely mid Feb I will push a .Net core version.

**Comment by paaland** [comment]
It's now march, any update on .Net core?

**Comment by mvadu** [comment]
@paaland good day to ask this question. I finally got it working this morning with Visual Studio 2017, and latest Core SDK. I will push the release in a day or two. I have to figure out the Travis CI for Core, and it will be ready to go.

**Comment by mvadu** [comment]
@paaland @ehjk do you care if the .Core support is present as a separate download on github or you want in a Nuget package? Nuget packaging with AppVeyor is little difficult when you have multiple projects, and I am facing issues there. If its a release #24 is ready.

**Comment by mvadu** [comment]
Fixed in #24

**Comment by mvadu** [comment]
Nuget package for Core is published as  [AdysTech.InfluxDB.Client.Net.Core](https://www.nuget.org/packages/AdysTech.InfluxDB.Client.Net.Core/)
