### ISSUE TITLE
Chunking support ?

### ISSUE THREAD

**Issue by gsokoll** [AdysTech/InfluxDB.Client.Net#23]
I was wondering if there is any plans to support chunked query responses ?
see https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/#chunking

**Comment by mvadu** [comment]
I will start working on this once adding .Net core support is complete. That is my current priority. Current ETA for chunking is end of this month.

**Comment by mvadu** [comment]
Added support for chunking with #29
