### ISSUE TITLE
Make Nanoseconds the default precision

### ISSUE THREAD

**Issue by jjathman** [AdysTech/InfluxDB.Client.Net#30]
I just started using this library, but I think one simple change would make it a little easier to work with, if the default precision for a InfluxDatapoint was Nanoseconds it would allow for users to not have to set either the precision or the timestamp of the object and have it correctly persist in to InfluxDB. Currently if neither field is set it will persist a DateTime.MinValue to InfluxDB. This is due to how the ToEpoch method currently works, if the TimePrecision component is not set then it returns 0 as the value.

Alternatively ToEpoch could just use Nanoseconds as the default precision if it isn't set, or throw an exception to make it clear that parameter must be set.

**Comment by mvadu** [comment]
Thank you @jjathman for this find.. I am leaning towards defaulting to nano second. That way I think I will default to InflxDB native behavior.

**Comment by jjathman** [comment]
This is great! Thanks for making this change, I think it's a nice sensible default behavior.
