### ISSUE TITLE
Max OSX: Using VS for Mac. Calling PostPointsAsync fails

### ISSUE THREAD

**Issue by hoihoi8** [AdysTech/InfluxDB.Client.Net#34]
Calling PostPointsAsync produces the following error:
mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)

Using a InfluxDBClient with no username/password, and no retention policy

Manual Curl calls to submit data work, so DB is setup and working

Thanks

**Comment by mvadu** [comment]
@hoihoi8 I don't use any mutex in the codebase, but that could be used by underlying .Net core. Could you please give me a stack trace for the exception?

**Comment by mvadu** [comment]
@hoihoi8 I don't think you are running this with .Net Core. With core, you don't need to run with mono. Since the exception you mentioned is about mono, I am closing this issue. Please try [installing Core ](http://www.microsoft.com/net/core#macos) and try again.
