### ISSUE TITLE
InfluxDBClient: Authentication attempts fail if password contains non-ASCII chars

### ISSUE THREAD

**Issue by maxee** [AdysTech/InfluxDB.Client.Net#38]
Then trying to connect to an InfluxDB instance the authentication with the instance fails if one's password contains non-ASCII chars such as `§`.

If the password contains ASCII-chars only, everything works fine.

This issue is caused by encoding both password and username as ASCII in InfluxDBClient.cs:

```
Convert.ToBase64String(System.Text.ASCIIEncoding.ASCII.GetBytes($"{InfluxDBUserName}:{InfluxDBPassword}")));
```

**Comment by mvadu** [comment]
Thank you for the find @maxee I will fix it in a day or two.. Currently not able to test my fix due to an issue with [influxdb#8573](https://github.com/influxdata/influxdb/issues/8573)

**Comment by mvadu** [comment]
@maxee can you confirm if the password works for you if you use the CLI? I am trying to fix this issue, and could not get Influx to accept the non ascii password. Refer [Influx#8620](https://github.com/influxdata/influxdb/issues/8620)

**Comment by maxee** [comment]
@mvadu I'm sure it is working on an Ubuntu 16.04.x LTS machine running InfluxDB v1.2.4.

Tried it again with further non-ASCII chars and it worked:

```
> CREATE USER test123 WITH PASSWORD 'test123€€€üöä§' WITH ALL PRIVILEGES
> exit
root@influx:~# influx -username test123 -password 'test123€€€üöä§'
Connected to http://localhost:8086 version 1.2.0
InfluxDB shell version: 1.2.4
> show databases
name: databases
name
----
_internal
xxxx
xxxx
xxxx
```

**Comment by mvadu** [comment]
@maxee thank you for getting back.. I was able to fix my test script and test the actual fix for this issue. Can you please give the new version a try and confirm?
