### ISSUE TITLE
Need to issue a "DELETE FROM {Measurement} WHERE ..." query

### ISSUE THREAD

**Issue by TGG-Solutions** [AdysTech/InfluxDB.Client.Net#41]
Can't see an obvious way to do this. Any advice?

**Comment by mvadu** [comment]
I would love to implement this. How are you proposing to pass the `where` clause? as a plain string?

**Comment by TGGsolutionsLtd** [comment]
Ideally, for my simple use cases, yes. I have just hacked together this for now:

public async Task<bool> DeleteValuesAsync(string dbName, string deleteQuery)
        {
            HttpResponseMessage response = await GetAsync(new Dictionary<string, string>() { { "db", dbName }, { "q", deleteQuery } });
            return (response.StatusCode == HttpStatusCode.OK);
        }

**Comment by mvadu** [comment]
Fixed in #51

**Comment by STilow** [comment]
Is it still not possible to use WHERE clause?
