### ISSUE TITLE
Why change case of tags?

### ISSUE THREAD

**Issue by hankbeasley** [AdysTech/InfluxDB.Client.Net#42]
``` var header = char.ToUpper(series.Columns[col][0]) + series.Columns[col].Substring(1);```

that line of code makes this library hard to deal with.

**Comment by mvadu** [comment]
@hankbeasley It should have been removed when I open sourced my library. In my original use case I was doing this as "beautification" to show the header in camel case. Thanks for bringing this up. I will remove this in the next minor version release.

**Comment by mvadu** [comment]
With #51, `GetInfluxSeries` has an optional parameter `SafePropertyNames` which is `true` by default but can be false to turn off these beautification.
