### ISSUE TITLE
InfluxDBException: invalid field format

### ISSUE THREAD

**Issue by volkanalkilic** [AdysTech/InfluxDB.Client.Net#47]
I get the following error when writing data;
![image](https://user-images.githubusercontent.com/14903319/46283531-4d1b0380-c57d-11e8-95fd-1cdbac4c7278.png)

**Comment by mvadu** [comment]
Your value seems to be a text. ` 0` i.e. zero with a space. Is that by design?

**Comment by mvadu** [comment]
Please reopen it if you have an update.
