### ISSUE TITLE
Providing InfluxUrl with trailing slash "/" result in error during QueryMultiSeriesAsync

### ISSUE THREAD

**Issue by jasase** [AdysTech/InfluxDB.Client.Net#54]
When creating the InfluxDBClient with an URL that contains a trailing "/" like this one

`var influxDbClient = new InfluxDBClient("http://localhost:8086/", "username", "password");`

a query with `influxDbClient.QueryMultiSeriesAsync()` throwing a `AdysTech.InfluxDB.Client.Net.ServiceUnavailableException`.

Due to the trailing slash an invalid GET Request is create: `http://localhost:8086//query?db=_internal&q=SHOW+STATS&epoch=n`

**Comment by mvadu** [comment]
Thanks for catching this @jasase , I just fixed it.
