### ISSUE TITLE
 InfluxDB service is not available

### ISSUE THREAD

**Issue by shoabshah** [AdysTech/InfluxDB.Client.Net#64]
Hi There,

Scenario:
We have a Linux (Unbuntu) box on which we have configured TIG (Telegraf InfluxDB and Garafana) stack. It is working as expected.

Requirement:
We want to be able to access InfluxDB from a c# application.

Actions done:
Following the steps mentioned at [https://www.nuget.org/packages/AdysTech.InfluxDB.Client.Net](url) and with below code we tried retrieving data.
`class Program
    {
        static void Main(string[] args)
        {
            callMethod();
            System.Threading.Thread.Sleep(100000);
            Console.Read();
        }

        public static async void callMethod()
        {
            Program obj = new Program();
            Task<List<string>> data = obj.GetData();
            List<string> res = await data;
        }

        public async Task<List<string>> GetData()
        {
            InfluxDBClient client = new InfluxDBClient("http://serverIP:8086", "dbusername", "dbpassword");
            List<String> dbNames = await client.GetInfluxDBNamesAsync();
            return dbNames;
        }
    }`

Error:
Getting below exception

> An exception of type 'AdysTech.InfluxDB.Client.Net.ServiceUnavailableException' occurred in mscorlib.dll but was not handled in user code
> 
> Additional information: InfluxDB service is not available

> 

> 

Kindly advise what are we missing / doing incorrect.

**Comment by bqstony** [comment]
Look at the unit tests and the TestSetup.ps1 script. Maybe you can find something that is different with your setup...

**Comment by svengl** [comment]
I had the same issues and it took me quite a while to figure out that it actually was a proxy problem! 
Try setting the correct proxy settings in internet explorer (the library uses system settings). If it is on a local LAN, set exceptions for the required local network to bypass the proxy.
