### ISSUE TITLE
Is there anyway to delete an existing database?

### ISSUE THREAD

**Issue by Gothic-X** [AdysTech/InfluxDB.Client.Net#67]
Is there any native support for deleting a database?

If not, is the best solution to use `QueryMultiSeriesAsync` with the following query syntax:
`DROP DATABASE <database_name>`

**Comment by mvadu** [comment]
yeah, no native methods yet. Influx recently responds with an error response (http 200, with a message) for DML in Get (which is used in `QueryMultiSeriesAsync`). Can you give it a shot and confirm it works? if not I will try to add a native method.

**Comment by Gothic-X** [comment]
Will do. I'll let you know the outcome

**Comment by Gothic-X** [comment]
@mvadu - I was able to drop the database using the following code.

```
// Delete the data source
await client.QueryMultiSeriesAsync(database, $"DROP DATABASE {database}");
```
