### ISSUE TITLE
Writing data points to DB

### ISSUE THREAD

**Issue by STilow** [AdysTech/InfluxDB.Client.Net#68]
Hello, 
I need to write a collection of points into existed measurement, so I tried the code from an example of using client.PostPointAsync. But, instead of just adding new entries into a measurment, it creates aditional tags and fields. Is it possible  just to write a collection of entries (or points) with a single command?

**Comment by mvadu** [comment]
You should be able to as long as you add the same tags (may be different values) and fields that are in your existing measurement. 

In the example below you can see we insert 5000 points in one run, no matter how many times you run you should see only `TestDate` and `TestTime` as tags.

```
for (int i = 0; i < 5000; i++)
{
	var valMixed = new InfluxDatapoint<InfluxValueField>();
	valMixed.UtcTimestamp = DataGen.RandomDate(start, end);
	valMixed.Tags.Add("TestDate", today);
	valMixed.Tags.Add("TestTime", now);
	valMixed.UtcTimestamp = DateTime.UtcNow;
	valMixed.Fields.Add("Doublefield", new InfluxValueField(DataGen.RandomDouble()));
	valMixed.Fields.Add("Stringfield", new InfluxValueField(DataGen.RandomString()));
	valMixed.Fields.Add("Boolfield", new InfluxValueField(DateTime.Now.Ticks % 2 == 0));
	valMixed.Fields.Add("Int Field", new InfluxValueField(DataGen.RandomInt()));
	valMixed.MeasurementName = measurementName;
	valMixed.Precision = (TimePrecision)(DataGen.RandomInt() % 6) + 1;
	points.Add(valMixed);
}

var r = await client.PostPointsAsync(dbName, points);
Assert.IsTrue(points.TrueForAll(p => p.Saved == true), "PostPointsAsync did not save all points");
```
