### ISSUE TITLE
What's the easiest way to count the entries in the measurement?

### ISSUE THREAD

**Issue by SkyGTRx5** [AdysTech/InfluxDB.Client.Net#69]
Hi!
II'm using your tool for working with our DB and it works fine. I've got a lot of data to to write and read. No problem. But then I faced a task just to count the number of entries inside the measurement, and I'm alittle bit stuck...
IThe only way I found how to get the number is using 
**var countQuery = $"select Count(*) from \"{measurment}\"";
var data = await client.QueryMultiSeriesAsync(_influxOptions.InfluxDbName, countQuery);**
totalNumberOfEntries += int.Parse(data.First().Entries.First().Count_eventID);
But I always need to specify the field name (in this case its 'event_ID') which is different for every measurements.
So, maybe there's an easier way to get the number?

**Comment by mvadu** [comment]
I am working on a helper method which should expose this data. Please give me few days.

**Comment by SkyGTRx5** [comment]
Hi! No problem, I'm not pushin))
Actually we solved this problem in bit complicated way I think, but it works. 
I created a method to identify the name of the first field key name from a measurement and then used something like this: 

var countQuery = $"SELECT Count(*) FROM \"{measurement}\"";
var data = await client.QueryMultiSeriesAsync(_influxOptions.InfluxDbName, countQuery);
var entries = data.SelectMany(serie => serie.Entries.Select(entry => (IDictionary<string, object>)entry));
            var firstEntry = entries.First();
            var key = $"Count_{fieldKeyName}";     // I identified this name in anathor method
            var entriesCount = firstEntry.ContainsKey(key)
                ? int.Parse(firstEntry[key].ToString())
                : 0;

**Comment by mvadu** [comment]
#73 should give you this in a handy structure
![image](https://user-images.githubusercontent.com/8618235/66257867-3bf66b00-e76c-11e9-905f-b4f1fba07c7c.png)
