### ISSUE TITLE
chunk / array for insert

### ISSUE THREAD

**Issue by jhalbrecht** [AdysTech/InfluxDB.Client.Net#70]
For grins and to see
* performance differences between MariaDB and InfluxDB 
* have a data set to learn about retention policy and downsampling
-- From some reading on the downsampling I'm not sure this dataset will help as if I'm reading correctly  calculations for retention and downsampling are performed on the fly during input and the retention period.

I wrote some dotnet to read ~1.6 million rows of perhaps five years of temperature data from several sensors.

It's not quite finished running... my estimate is ~twenty two hours. :-)

- Is there anything I might do to this code to speed it up?
- Is there a batch or array insert something like the chunked queries? But for writing inserts.
- Other tools I might consider for an ~ 1 time import?

```
foreach (var row in tncrows){
    rowCounter++;
    if ((rowCounter % 100) == 0){
        TimeSpan duration = DateTime.Now - startTime;
        Console.WriteLine($"Started: {startTime} current time: {DateTime.Now} duration: {duration:hh\\:mm\\:ss} row: {rowCounter} row.Id: {row.Id}");
    }
    // TODO: what does it cost to new this up each time through the loop?
    // probably not much compared to the insert.
    // When I tried to reuse it creating it outside the loop I got an 
    // exception on the 2nd insert.
    // Perhaps a Fields.Replace("Id", new InfluxValueField(row.Id));

    var influxDatapoint = new InfluxDatapoint<InfluxValueField>();
    influxDatapoint.Fields.Add("Id", new InfluxValueField(row.Id));
    influxDatapoint.Tags.Add("sensorId", row.sensorId);
    influxDatapoint.Fields.Add("fahrenheit", new InfluxValueField(row.fahrenheit));
    influxDatapoint.UtcTimestamp = Convert.ToDateTime(row.utcTime);
    influxDatapoint.MeasurementName = "tnctest";
    var r = await influxDBclient.PostPointAsync(Settings.InfluxDbName, influxDatapoint);
    // influxDatapoint.dispose;
}
```
```
    public class tnc {
        public int Id { get; set; }
        public string utcTime { get; set; }
        public string sensorId { get; set; }
        public double fahrenheit { get; set; }
    }

```

**Comment by mvadu** [comment]
The idea is you fill in an array of `InfluxDataPoint` with data to the `PostPointAsync` and let the code take care of chunking it. You are currently inserting one point at a time, which is very inefficient way to do it. Please go through the samples in test cases, and you can see `TestPostPointsAsync_Batch()` where 2000 points gets inserted in one go. in your case, create a list like `var points = new List<IInfluxDatapoint>();` before your loop and add points to the list instead of posting it inside loop. Once you are out of the loop invoke `PostPointsAsync` to insert. Let me know how that goes.

**Comment by jhalbrecht** [comment]
I don't know how I missed; `A collection of points can be posted using await client.PostPointsAsync (dbName, points), where points can be collection of different types of InfluxDatapoint` in the ReadMe.md

This code ran considerably faster - in twelve minutes. One flaw I think it misses the last chunk if `a` is smaller than the `batchSize` in the for loop.

``` csharp
// int batchSize = 1000;
int batchSize = 25000;
for (int a = 0; a <= totalTncRows; a += batchSize) {
    var tncsToAdd = tncrows.Skip (a).Take (batchSize);
    var pointsToAdd = new List<IInfluxDatapoint> ();
    foreach (var row in tncsToAdd) {
        var influxDatapoint = new InfluxDatapoint<InfluxValueField> ();
        influxDatapoint.Fields.Add ("Id", new InfluxValueField (row.Id));
        influxDatapoint.Tags.Add ("sensorId", row.sensorId);
        influxDatapoint.Fields.Add ("fahrenheit", new InfluxValueField (row.fahrenheit));
        influxDatapoint.UtcTimestamp = Convert.ToDateTime (row.utcTime);
        influxDatapoint.MeasurementName = "tnctest";
        pointsToAdd.Add (influxDatapoint);
    }
    var r = await influxDBclient.PostPointsAsync ("ya_homeamation_test", pointsToAdd);
    duration = DateTime.Now - startTime;
    // Console.WriteLine ($"Started: {startTime} current time: {DateTime.Now} duration: {duration:hh\\:mm\\:ss} row: {rowCounter} row.Id: {row.Id}");
    Console.WriteLine ($"posted: {r} Started: {startTime} current time: {DateTime.Now} duration: {duration:hh\\:mm\\:ss} a: {a}" );
}
Console.WriteLine($"Finished.");

```

**Comment by mvadu** [comment]
Okay, some more modification needed..
`var r = await influxDBclient.PostPointsAsync ("ya_homeamation_test", pointsToAdd);` actually does a default batch of 255 points, which is for your 25k points, close to 100 round trips to Influx. You can actually pass the batch size to `PostPointsAsync` as third optional parameter. Try that. About the last chunk, I am not sure if its library issue. I have tests where it checks the posted points have been saved. If you can give me steps to reproduce (with the data) i can try it out.

**Comment by jhalbrecht** [comment]
ahh... So really I just need to make a single list of `List<IInfluxDatapoint> ()` from each row in the MariaDB tnc db (tncRows). And I can adjust the batch size in the `PostPointsAsync `
```

            var startTime = DateTime.Now;
            // int batchSize = 256;
            // int batchSize = 1000;
            // int batchSize = 10000;
            int batchSize = 25000;
            // int batchSize = 100000;

            var pointsToAdd = new List<IInfluxDatapoint> ();
            foreach (var row in tncRows)
            {
                var influxDatapoint = new InfluxDatapoint<InfluxValueField> ();
                influxDatapoint.Fields.Add ("Id", new InfluxValueField (row.Id));
                influxDatapoint.Tags.Add ("sensorId", row.sensorId);
                influxDatapoint.Fields.Add ("fahrenheit", new InfluxValueField (row.fahrenheit));
                influxDatapoint.UtcTimestamp = Convert.ToDateTime (row.utcTime);
                influxDatapoint.MeasurementName = "yatnctest";
                pointsToAdd.Add (influxDatapoint);
            }
            var r = await influxDBclient.PostPointsAsync ("ya_homeamation_test", pointsToAdd, batchSize);

            duration = DateTime.Now - startTime;
            Console.WriteLine ($"Finished. Start time: {startTime} current time: {DateTime.Now} Duration: {duration:hh\\:mm\\:ss} Batch size: {batchSize}");
     
```
I ran this code with some different batch sizes to the `PostPointsAsync`. a minute forty six seconds for 10,000 batchsize. Not bad at all.


```
Finished. Start time: 8/3/2019 12:48:50 PM current time: 8/3/2019 12:55:41 PM Duration: 00:06:50.9726682 (batchsize 256)
Finished. Start time: 8/3/2019 1:08:38 PM current time: 8/3/2019 1:11:33 PM Duration: 00:02:54 Batch size: 1000
Finished. Start time: 8/3/2019 1:26:14 PM current time: 8/3/2019 1:28:00 PM Duration: 00:01:46 Batch size: 10000
Finished. Start time: 8/3/2019 1:33:08 PM current time: 8/3/2019 1:36:36 PM Duration: 00:03:27 Batch size: 25000

```
