### ISSUE TITLE
very slow insert for large lists

### ISSUE THREAD

**Issue by thomasd3** [AdysTech/InfluxDB.Client.Net#72]
I am trying to insert a list with 800k points; each has 5 floats + a timestamp and a 1 minute resolution.

The data is very simple stock candles:

```
public class Candle
{
	public DateTime Timestamp;
	public float Open;
	public float High;
	public float Low;
	public float Close;
	public float Volume;
}
```

I am inserting the points this way:

    await _InfluxDb.PostPointsAsync("mydb", dataPoints, 10000);

the buffer size seems to have very little impact.

At the same time, inserting the same data through another C# driver (https://github.com/pootzko/InfluxDB.Net/), I get 3-4x the insertion speed.

What could be causing the problem?

**Comment by thomasd3** [comment]
After some testing, the slowdown is 100% contained in: ConvertToInfluxLineProtocol, in InfluxDataPoint.cs

I guess that's a the price to pay for having a flexible design; each point requires the allocation of two string builders + executing some linq code; maybe one solution may to be build the point step by step as parameters are added to it.

**Comment by mvadu** [comment]
Do you have a test data set that can be shared? I would like to use that as benchmark to tune. Its been a while I did any changes to that core logic, but no harm in revisiting.

**Comment by thomasd3** [comment]
there you go: https://we.tl/t-AjdADQiyjt

from what I see, the issue seems to be the many allocations of the stringbuilder class.

**Comment by mvadu** [comment]
@thomasd3 I made some tweaks to use same StringBuilder for the entire point instead of creating one for each the value. ALso went ahead and added gzip compression. On my local VM which also runs Influx i am getting 1 million points within 50 sec. Can you give the version in #73 a shot?

**Comment by thomasd3** [comment]
@mvadu , I'll be traveling all next week, but I will try as soon as I get back.
