### ISSUE TITLE
Does it support HTTPS queries?

### ISSUE THREAD

**Issue by kappayero** [AdysTech/InfluxDB.Client.Net#74]
Hello!
Apparently directly specifying an address with https://xxx.xxx.xxx.xxx:yyyy states that the database service is not working, even though a remote CLI can connect to it using HTTPS.

Does the library support HTTPS queries to InfluxDB? 
Thanks.

**Comment by mvadu** [comment]
It does since the core `HttpClient` handled the TLS. #56 also was added on top of http end point. The database service error is slightly generic. If you could capture the stack trace we can troubleshoot further.

**Comment by kappayero** [comment]
Hi! Thanks for the quick answer. Doing a quick test trying to query the available databases it throws an Exception with the following content:

___________________________________________________________________
ToString: AdysTech.InfluxDB.Client.Net.ServiceUnavailableException: InfluxDB service is not available
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.<QueryMultiSeriesAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AdysTech.InfluxDB.Client.Net.InfluxDBClient.<GetInfluxDBNamesAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Csys_Performance_Analyser.InfluxDB_Manager.<SaveToDatabaseAsync>d__18.MoveNext()

The program works well if the database is set only to use HTTP and the address given starts with http://... but when the DB is configured to work with HTTPS and the program is set with an https://... address the aforementioned exception is thrown.
Note: The database is using a Self Signed Certificate.

AdysTech/InfluxDB.Client.Net version 0.7.3.0

The database is reachable from the PC where the program is being executed using CLI:
C:\influxdb\influxdb-1.2.0-1>influx -ssl -unsafeSsl -host 172.16.143.46
Connected to https://172.16.143.46:8086 version 1.7.8
InfluxDB shell version: 1.2.0
>

InfluxDB is configured with the following:
[Http]
enabled = true
bind-address = ":8086"
log-enabled = true
https-enabled = true
https-certificate =  "/etc/ssl/influxdb-selfsigned.crt"
https-private-key =  "/etc/ssl/influxdb-selfsigned.key"


In-code Client declaration and usage:

internal class InfluxDB_Manager{
   private static InfluxDBClient DBClient;
   ...
   DBClient = new InfluxDBClient(string DBUserName, DBPassword); 
   internal static void InitialiseManager(string dbName, string dbusrname, string dbpsw)
        {
            DBClient = new InfluxDBClient("https://172.16.143.46:8086", dbusrname, dbpsw);
        }
   ...
   internal async Task SaveToDatabaseAsync()
        {
            try
            {                
                    List<String> dbNames = await DBClient.GetInfluxDBNamesAsync();
                    foreach (string name in dbNames)
                        Console.WriteLine(name);
               
            catch (Exception e)
            {                
                Console.WriteLine(e.ToString());
            }
        }
}


Thank you very much.

**Comment by mvadu** [comment]
ah.. its self signed cert!! that makes sense. `HttpClient` does not trust the self signed certs by default. I have not added any special handling to trust these certs. Technically it can be done, but as of now I don't see a use case for that. I assume you are using this self signed cert for local use. In that case you must be able to make your OS trust the cert (e.g. [windows](https://blogs.technet.microsoft.com/sbs/2008/05/08/installing-a-self-signed-certificate-as-a-trusted-root-ca-in-windows-vista/), [linux](https://serverfault.com/questions/730006/how-do-i-trust-a-self-signed-certificate)) that will make the .Net client trust that cert too.
