### ISSUE TITLE
How to get errors?

### ISSUE THREAD

**Issue by thomasd3** [AdysTech/InfluxDB.Client.Net#78]
I have a situation where I'm pushing data points and the call:

    var r = await _Client.PostPointAsync(_DatabaseName, p);

just returns 'false'...

but false is not really telling me anything about the problem; I don't know if it's a data issue, a connectivity issue, etc.

how can I get the actual error returned by the database?

**Comment by mvadu** [comment]
`PostPointAsync` returns false in only few cases. In most of the error situations it should throw an exception. 

Throws `InfluxDBException` after special processing to find the error reported by Influx 

- 400 BadRequest 

Throws `UnauthorizedAccessException` for these

- 401	Unauthorized 
- 502	BadGateway 
- 500	InternalServerError 
- 502 	Connection refused

I will add it to myy TODO list to throw in all non 204 status codes

**Comment by thomasd3** [comment]
I just had a 405 for trying to use http (not https) over cloudflare. this was returning false but no exception.
