### ISSUE TITLE
PostPointsAsync throw System.OutOfMemoryException

### ISSUE THREAD

**Issue by hx425072624** [AdysTech/InfluxDB.Client.Net#79]
after the program ran a while ,it always throw System.OutOfMemoryException.how to find the error?
![image](https://user-images.githubusercontent.com/23489383/67924280-2b120b80-fbeb-11e9-8cda-9d8cc5d7fd92.png)

**Comment by mvadu** [comment]
how many points are you trying to post in each try? Can you try passing third argument with a fixed smaller number (say 1000 for testing purpose)?
