### ISSUE TITLE
Can't be used from F#

### ISSUE THREAD

**Issue by thomasd3** [AdysTech/InfluxDB.Client.Net#81]
See: https://stackoverflow.com/questions/58936062/weird-c-sharp-f-difference-in-a-declaration-code-comiling-in-c-sharp-but-not?noredirect=1#comment104131249_58936062

**Comment by mvadu** [comment]
I think Scott did solve the issue for you in https://stackoverflow.com/questions/58999141/influxvaluefield-that-implements-two-interfaces-incompatible-in-f
