### ISSUE TITLE
occur an error because force casting when add key

### ISSUE THREAD

**Issue by yhw9999** [AdysTech/InfluxDB.Client.Net#88]
https://github.com/AdysTech/InfluxDB.Client.Net/blob/0ac160259cc76f9a23ac2c92f6cc07fa3b49cdd3/src/DataStructures/InfluxDBClient.cs#L678

i have a question. why change first character to uppercase?
and occur an error because force casting when add key.

could you fix it?

**Comment by mvadu** [comment]
Its controlled by an optional parameter `SafePropertyNames`. Refer to #42 for more discussion on that topic. Few of the valid tag names becomes invalid due to them being .net reserved words. Having the first letter capital makes them safe to use in .Net world and Influx world.
