### ISSUE TITLE
confused by "Integer" support

### ISSUE THREAD

**Issue by BrannonKing** [AdysTech/InfluxDB.Client.Net#9]
According to the InfluxDB documentation, it's integer support is 64bit long. That makes me think you should support the .NET "long" type. "Integer" with a capital "I" seemed to imply "int" in C# landw; there is no `System.Integer` though.

**Comment by mvadu** [comment]
@BrannonKing you are right, I should change it to long from int. Will do it tonight.

**Comment by mvadu** [comment]
Closed by #10
