### ISSUE TITLE
PostPointsAsync method is so slow in linux os

### ISSUE THREAD

**Issue by jinkyu93** [AdysTech/InfluxDB.Client.Net#90]
hi
I've used this library on my dot net core solution.
when I test in window os, this library was not slow.
but in linux os, PostPointsAsync was so slow.
I checked why. and I find InfluxValueField.ToString is so slow.
if InfluxValueField is double or float, you use String.Format method.
but when I tested in linux os, this code so slow. so I changed this code just toString.
after changing, PostPointsAsync was not slow in linux os.

I have some question. why use String.Format method?

my development environment is
window : window 10
linux : centos 7

check this logic please.

![InfluxValueField](https://user-images.githubusercontent.com/29620483/75207717-e5daa080-57bc-11ea-9b68-a09138635dbe.PNG)

**Comment by mvadu** [comment]
Please see #3. InfluxDB assumes decimal separator to be a `.`, but in other locale settings system default could be `,` which makes the Influx line protocol to break. If the  `String.Format` is slow on linux then we should probably raise in .netcore. If its just in `InfluxValueField.ToString` I can take a look to optimize it.

**Comment by yyjdelete** [comment]
CultureInfo.InvariantCulture?

**Comment by jinkyu93** [comment]
How about 
"CultureInfo.GetCultureInfo("en-us")"
instead of
"new CultureInfo("en-us")"

when I change this code, I got a fast speed in linux os 
you made to create every time CultureInfo object on call ToString in InfluxValueField. that is seem to be inefficient.

**Comment by mvadu** [comment]
@jinkyu93 that is a brilliant suggestion.. Now wondering why I did not think about it.. I will try to push an update this weekend..
