### ISSUE TITLE
Improve error handling for 400

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AdysTech/InfluxDB.Client.Net#96]
I get next error:

```
HTTP/1.1 400 Bad Request
Server: nginx/1.12.2
Date: Fri, 22 May 2020 17:12:34 GMT
Content-Type: application/json
Content-Length: 99
Connection: keep-alive

{"statement_id":0,"error":"query not allowed: accessing database \"foobarbaz\" is not allowed"}
```

And see:
![image](https://user-images.githubusercontent.com/757125/82692876-28e7cb00-9c69-11ea-9cc3-998f3e130dff.png)

Expected:

If you cannot parse resonces, at least provide it error code and inner text

**Comment by mvadu** [comment]
I will work on it.
