### ISSUE TITLE
Switch to .NET Standard 2.1 prevent use from applications using .NET framework

### ISSUE THREAD

**Issue by tboehme** [AdysTech/InfluxDB.Client.Net#97]
With the latest version, the .NET Standard version has been raised from 2.0 to 2.1.

This prevents using the library in any .NET framework code, as even the latest .NET framework does only support .NET Standard 2.0.

Is there a specific reason, why the library was changed to .NET Standard 2.1?

**Comment by mvadu** [comment]
@tboehme sorry for delay in responding. I was updating my other repo and did the same for this one too. I will revert it back.
